AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - test/dummy/**/*

require:
  - rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/ClassLength:
  Exclude:
    - lib/serialize_attributes/store.rb
    - test/**/*_test.rb
